version: '3'
networks:
    local:
services:
    flask:
        build: .
        container_name: flask-api
        ports:
            - 5000:5000
        volumes:
            - .:/app 
        links:
            - mysql
        # depends_on:
        #     - db
        # command: --default-authentication-plugin=mysql_native_password
        # restart: apos
    mysql:
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_DATABASE: react
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
        ports:
        - "3307:3306"
        volumes:
            - ./db/mysql/conf/my.cnf:/etc/my.cnf.d/
            - ./db/mysql/logs:/logs
            - ./db/mysql/data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8000:80
        environment:
            MYSQL_DATABASE: react
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db

    
